version: '3.7'

services:
  ravendb:
    image: ravendb/ravendb:5.4-ubuntu-latest
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - type: bind
        source: ./data
        target: /opt/RavenDB/Server/RavenData   